src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ServiceDescription;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\GreaterThan(0)
     */
    private $ServicePrice;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ServiceCompleteDate;

    /**
     * @ORM\ManyToOne(targetEntity=Custom::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Custom;

    /**
     * @ORM\ManyToOne(targetEntity=Bay::class, inversedBy="Service")
     */
    private $Bay;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfWork::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TypeOfWork;

    /**
     * @ORM\ManyToOne(targetEntity=Worker::class, inversedBy="Service")
     */
    private $Worker;

    /**
     * @ORM\OneToMany(targetEntity=Material::class, mappedBy="Service")
     */
    private $Material;

    public function __construct()
    {
        $this->Material = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getServiceDescription(): ?string
    {
        return $this->ServiceDescription;
    }

    public function setServiceDescription(?string $ServiceDescription): self
    {
        $this->ServiceDescription = $ServiceDescription;

        return $this;
    }

    public function getServicePrice(): ?string
    {
        return $this->ServicePrice;
    }

    public function setServicePrice(string $ServicePrice): self
    {
        $this->ServicePrice = $ServicePrice;

        return $this;
    }

    public function getServiceCompleteDate(): ?\DateTimeInterface
    {
        return $this->ServiceCompleteDate;
    }

    public function setServiceCompleteDate(?\DateTimeInterface $ServiceCompleteDate): self
    {
        $this->ServiceCompleteDate = $ServiceCompleteDate;

        return $this;
    }

    public function getCustom(): ?Custom
    {
        return $this->Custom;
    }

    public function setCustom(?Custom $Custom): self
    {
        $this->Custom = $Custom;

        return $this;
    }

    public function getBay(): ?Bay
    {
        return $this->Bay;
    }

    public function setBay(?Bay $Bay): self
    {
        $this->Bay = $Bay;

        return $this;
    }

    public function getTypeOfWork(): ?TypeOfWork
    {
        return $this->TypeOfWork;
    }

    public function setTypeOfWork(?TypeOfWork $TypeOfWork): self
    {
        $this->TypeOfWork = $TypeOfWork;

        return $this;
    }

    public function getWorker(): ?Worker
    {
        return $this->Worker;
    }

    public function setWorker(?Worker $Worker): self
    {
        $this->Worker = $Worker;

        return $this;
    }

    /**
     * @return Collection<int, Material>
     */
    public function getMaterial(): Collection
    {
        return $this->Material;
    }

    public function addMaterial(Material $material): self
    {
        if (!$this->Material->contains($material)) {
            $this->Material[] = $material;
            $material->setService($this);
        }

        return $this;
    }

    public function removeMaterial(Material $material): self
    {
        if ($this->Material->removeElement($material)) {
            // set the owning side to null (unless already changed)
            if ($material->getService() === $this) {
                $material->setService(null);
            }
        }

        return $this;
    }
}

src/Entity/Worker.php
<?php

namespace App\Entity;

use App\Repository\WorkerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkerRepository::class)
 */
class Worker
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $WorkerFirstName;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $WorkerMiddleName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $WorkerLastName;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $WorkerPhone;

    /**
     * @ORM\ManyToOne(targetEntity=Bay::class, inversedBy="Worker")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Bay;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfWork::class, inversedBy="Worker")
     */
    private $TypeOfWork;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Worker")
     */
    private $Service;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWorkerFirstName(): ?string
    {
        return $this->WorkerFirstName;
    }

    public function setWorkerFirstName(string $WorkerFirstName): self
    {
        $this->WorkerFirstName = $WorkerFirstName;

        return $this;
    }

    public function getWorkerMiddleName(): ?string
    {
        return $this->WorkerMiddleName;
    }

    public function setWorkerMiddleName(string $WorkerMiddleName): self
    {
        $this->WorkerMiddleName = $WorkerMiddleName;

        return $this;
    }

    public function getWorkerLastName(): ?string
    {
        return $this->WorkerLastName;
    }

    public function setWorkerLastName(string $WorkerLastName): self
    {
        $this->WorkerLastName = $WorkerLastName;

        return $this;
    }

    public function getWorkerPhone(): ?string
    {
        return $this->WorkerPhone;
    }

    public function setWorkerPhone(string $WorkerPhone): self
    {
        $this->WorkerPhone = $WorkerPhone;

        return $this;
    }

    public function getBay(): ?Bay
    {
        return $this->Bay;
    }

    public function setBay(?Bay $Bay): self
    {
        $this->Bay = $Bay;

        return $this;
    }

    public function getTypeOfWork(): ?TypeOfWork
    {
        return $this->TypeOfWork;
    }

    public function setTypeOfWork(?TypeOfWork $TypeOfWork): self
    {
        $this->TypeOfWork = $TypeOfWork;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setWorker($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getWorker() === $this) {
                $service->setWorker(null);
            }
        }

        return $this;
    }
}

src/Form/WorkerType.php
<?php

namespace App\Form;

use App\Entity\Worker;
use App\Form\DataTransformer\BayToStringTransformer;
use App\Form\DataTransformer\TypeOfWorkToStringTransformer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkerType extends AbstractType
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('WorkerFirstName')
            ->add('WorkerMiddleName')
            ->add('WorkerLastName')
            ->add('WorkerPhone')
            ->add('Bay', TextType::class, array(
                // сообщение валидации при ошибке преобразователя данных
                'invalid_message' => 'That is not a valid issue number',
            ))
            ->add('TypeOfWork', HiddenType::class, array(
                // сообщение валидации при ошибке преобразователя данных
                'invalid_message' => 'That is not a valid issue number',
            ))
        ;

        $builder->get('Bay')->addModelTransformer(new BayToStringTransformer($this->em));
        $builder->get('TypeOfWork')->addModelTransformer(new TypeOfWorkToStringTransformer($this->em));
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Worker::class,
        ]);
    }
}

src/Controller/WorkerController.php
<?php

namespace App\Controller;

use App\Entity\Worker;
use App\Form\WorkerType;
use App\Repository\ServiceRepository;
use App\Repository\WorkerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/worker")
 */
class WorkerController extends AbstractController
{
    /**
     * @Route("/", name="app_worker_index", methods={"GET"})
     */
    public function index(WorkerRepository $workerRepository): Response
    {
        return $this->render('worker/index.html.twig', [
            'workers' => $workerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_worker_new", methods={"GET", "POST"})
     */
    public function new(Request $request, WorkerRepository $workerRepository): Response
    {
        $worker = new Worker();
        $form = $this->createForm(WorkerType::class, $worker);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $workerRepository->add($worker, true);

            return $this->redirectToRoute('app_worker_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('worker/new.html.twig', [
            'worker' => $worker,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_worker_show", methods={"GET"})
     */
    public function show(Worker $worker, ServiceRepository $serviceRepository): Response
    {
        $services = $serviceRepository->findBy(['Worker' => $worker->getId()]);

        return $this->render('worker/show.html.twig', [
            'worker' => $worker,
            'services' => $services,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_worker_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Worker $worker, WorkerRepository $workerRepository): Response
    {
        $form = $this->createForm(WorkerType::class, $worker);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $workerRepository->add($worker, true);

            return $this->redirectToRoute('app_worker_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('worker/edit.html.twig', [
            'worker' => $worker,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_worker_delete", methods={"POST"})
     */
    public function delete(Request $request, Worker $worker, WorkerRepository $workerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $worker->getId(), $request->request->get('_token'))) {
            $workerRepository->remove($worker, true);
        }

        return $this->redirectToRoute('app_worker_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/worker/_delete_form.html.twig
<form method="post" action="{{ path('app_worker_delete', {'id': worker.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ worker.id) }}">
    <button class="btn btn-outline-danger">Удалить</button>
</form>

templates/worker/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/worker/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование работника{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Редактор работника</h1>

        {{ include('worker/_form.html.twig', {'button_label': 'Обновить'}) }}
        <div class="d-grid gap-2 d-md-block">
            <a href="{{ path('app_worker_index') }}" class="btn btn-outline-primary"
               style="margin-top: 1em; margin-bottom: 1em">К списку работников</a>

            {{ include('worker/_delete_form.html.twig') }}
        </div>

    </div>
{% endblock %}

templates/worker/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Работники{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Работники</h1>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for worker in workers %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ worker.workerPhone }}</h5>
                            <p class="card-text">{{ worker.workerMiddleName }} {{ worker.workerFirstName }} {{ worker.workerLastName }}</p>
                            <p>
                                <a href="{{ path('app_worker_show', {'id': worker.id}) }}" class="btn btn-outline-primary">Подробнее</a>
                                <a href="{{ path('app_worker_edit', {'id': worker.id}) }}" class="btn btn-outline-secondary">Редактировать</a>
                            </p>
                        </div>
                    </div>
                </div>

            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
        </div>
        <p style="margin-top: 1em">
            <a href="{{ path('app_worker_new') }}" class="btn btn-primary">Добавить работника</a>
            <a href="{{ path('app_main_index') }}" class="btn btn-outline-success">На главную</a>
        </p>
    </div>
{% endblock %}

templates/worker/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление работника{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Добавить нового работника</h1>

        {{ include('worker/_form.html.twig') }}

        <a href="{{ path('app_worker_index') }}" class="btn btn-outline-primary" style="margin-top: 1em;">К списку
            работников</a>
    </div>
{% endblock %}

templates/worker/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ worker.workerMiddleName }} {{ worker.workerFirstName }} {{ worker.workerLastName }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>{{ worker.workerMiddleName }} {{ worker.workerFirstName }} {{ worker.workerLastName }}</h1>

        <p>Телефон: {{ worker.workerPhone }}</p>
        <h3>Работы:</h3>
        {% for service in services %}
            <p>
                <a href="{{ path('app_service_show', {'id': service.id}) }}">{{ service.serviceDescription}}</a>
            </p>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}

        <p style="margin-bottom: 1em; margin-top: 1em;">
            <a href="{{ path('app_worker_index') }}" class="btn btn-outline-primary">К списку работников</a>

            <a href="{{ path('app_worker_edit', {'id': worker.id}) }}"
               class="btn btn-outline-secondary">Редактировать</a>
        </p>
        {{ include('worker/_delete_form.html.twig') }}
    </div>
{% endblock %}