src/Entity/Bay.php
<?php

namespace App\Entity;

use App\Repository\BayRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BayRepository::class)
 */
class Bay
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $BayType;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Bay")
     */
    private $Service;

    /**
     * @ORM\OneToMany(targetEntity=Worker::class, mappedBy="Bay")
     */
    private $Worker;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
        $this->Worker = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBayType(): ?string
    {
        return $this->BayType;
    }

    public function setBayType(string $BayType): self
    {
        $this->BayType = $BayType;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setBay($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getBay() === $this) {
                $service->setBay(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Worker>
     */
    public function getWorker(): Collection
    {
        return $this->Worker;
    }

    public function addWorker(Worker $worker): self
    {
        if (!$this->Worker->contains($worker)) {
            $this->Worker[] = $worker;
            $worker->setBay($this);
        }

        return $this;
    }

    public function removeWorker(Worker $worker): self
    {
        if ($this->Worker->removeElement($worker)) {
            // set the owning side to null (unless already changed)
            if ($worker->getBay() === $this) {
                $worker->setBay(null);
            }
        }

        return $this;
    }
}

src/Entity/Custom.php
<?php

namespace App\Entity;

use App\Repository\CustomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomRepository::class)
 */
class Custom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $CarInformation;

    /**
     * @ORM\Column(type="date")
     */
    private $OrderDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderEndDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderPayDate;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="Custom")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Custom", orphanRemoval=true)
     */
    private $Service;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarInformation(): ?string
    {
        return $this->CarInformation;
    }

    public function setCarInformation(string $CarInformation): self
    {
        $this->CarInformation = $CarInformation;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->OrderDate;
    }

    public function setOrderDate(\DateTimeInterface $OrderDate): self
    {
        $this->OrderDate = $OrderDate;

        return $this;
    }

    public function getOrderEndDate(): ?\DateTimeInterface
    {
        return $this->OrderEndDate;
    }

    public function setOrderEndDate(?\DateTimeInterface $OrderEndDate): self
    {
        $this->OrderEndDate = $OrderEndDate;

        return $this;
    }

    public function getOrderPayDate(): ?\DateTimeInterface
    {
        return $this->OrderPayDate;
    }

    public function setOrderPayDate(?\DateTimeInterface $OrderPayDate): self
    {
        $this->OrderPayDate = $OrderPayDate;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setCustom($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getCustom() === $this) {
                $service->setCustom(null);
            }
        }

        return $this;
    }
}

src/Entity/Material.php
<?php

namespace App\Entity;

use App\Repository\MaterialRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MaterialRepository::class)
 */
class Material
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $MaterialName;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\GreaterThan(0)
     */
    private $MaterialPrice;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $MaterialDescription;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(0)
     */
    private $MaterialAmount;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $MaterialMeasure;

    /**
     * @ORM\ManyToOne(targetEntity=Service::class, inversedBy="Material")
     */
    private $Service;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMaterialName(): ?string
    {
        return $this->MaterialName;
    }

    public function setMaterialName(string $MaterialName): self
    {
        $this->MaterialName = $MaterialName;

        return $this;
    }

    public function getMaterialPrice(): ?string
    {
        return $this->MaterialPrice;
    }

    public function setMaterialPrice(string $MaterialPrice): self
    {
        $this->MaterialPrice = $MaterialPrice;

        return $this;
    }

    public function getMaterialDescription(): ?string
    {
        return $this->MaterialDescription;
    }

    public function setMaterialDescription(?string $MaterialDescription): self
    {
        $this->MaterialDescription = $MaterialDescription;

        return $this;
    }

    public function getMaterialAmount(): ?int
    {
        return $this->MaterialAmount;
    }

    public function setMaterialAmount(int $MaterialAmount): self
    {
        $this->MaterialAmount = $MaterialAmount;

        return $this;
    }

    public function getMaterialMeasure(): ?string
    {
        return $this->MaterialMeasure;
    }

    public function setMaterialMeasure(string $MaterialMeasure): self
    {
        $this->MaterialMeasure = $MaterialMeasure;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ServiceDescription;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\GreaterThan(0)
     */
    private $ServicePrice;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ServiceCompleteDate;

    /**
     * @ORM\ManyToOne(targetEntity=Custom::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Custom;

    /**
     * @ORM\ManyToOne(targetEntity=Bay::class, inversedBy="Service")
     */
    private $Bay;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfWork::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TypeOfWork;

    /**
     * @ORM\ManyToOne(targetEntity=Worker::class, inversedBy="Service")
     */
    private $Worker;

    /**
     * @ORM\OneToMany(targetEntity=Material::class, mappedBy="Service")
     */
    private $Material;

    public function __construct()
    {
        $this->Material = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getServiceDescription(): ?string
    {
        return $this->ServiceDescription;
    }

    public function setServiceDescription(?string $ServiceDescription): self
    {
        $this->ServiceDescription = $ServiceDescription;

        return $this;
    }

    public function getServicePrice(): ?string
    {
        return $this->ServicePrice;
    }

    public function setServicePrice(string $ServicePrice): self
    {
        $this->ServicePrice = $ServicePrice;

        return $this;
    }

    public function getServiceCompleteDate(): ?\DateTimeInterface
    {
        return $this->ServiceCompleteDate;
    }

    public function setServiceCompleteDate(?\DateTimeInterface $ServiceCompleteDate): self
    {
        $this->ServiceCompleteDate = $ServiceCompleteDate;

        return $this;
    }

    public function getCustom(): ?Custom
    {
        return $this->Custom;
    }

    public function setCustom(?Custom $Custom): self
    {
        $this->Custom = $Custom;

        return $this;
    }

    public function getBay(): ?Bay
    {
        return $this->Bay;
    }

    public function setBay(?Bay $Bay): self
    {
        $this->Bay = $Bay;

        return $this;
    }

    public function getTypeOfWork(): ?TypeOfWork
    {
        return $this->TypeOfWork;
    }

    public function setTypeOfWork(?TypeOfWork $TypeOfWork): self
    {
        $this->TypeOfWork = $TypeOfWork;

        return $this;
    }

    public function getWorker(): ?Worker
    {
        return $this->Worker;
    }

    public function setWorker(?Worker $Worker): self
    {
        $this->Worker = $Worker;

        return $this;
    }

    /**
     * @return Collection<int, Material>
     */
    public function getMaterial(): Collection
    {
        return $this->Material;
    }

    public function addMaterial(Material $material): self
    {
        if (!$this->Material->contains($material)) {
            $this->Material[] = $material;
            $material->setService($this);
        }

        return $this;
    }

    public function removeMaterial(Material $material): self
    {
        if ($this->Material->removeElement($material)) {
            // set the owning side to null (unless already changed)
            if ($material->getService() === $this) {
                $material->setService(null);
            }
        }

        return $this;
    }
}

src/Entity/Worker.php
<?php

namespace App\Entity;

use App\Repository\WorkerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkerRepository::class)
 */
class Worker
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $WorkerFirstName;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $WorkerMiddleName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $WorkerLastName;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $WorkerPhone;

    /**
     * @ORM\ManyToOne(targetEntity=Bay::class, inversedBy="Worker")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Bay;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfWork::class, inversedBy="Worker")
     */
    private $TypeOfWork;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Worker")
     */
    private $Service;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWorkerFirstName(): ?string
    {
        return $this->WorkerFirstName;
    }

    public function setWorkerFirstName(string $WorkerFirstName): self
    {
        $this->WorkerFirstName = $WorkerFirstName;

        return $this;
    }

    public function getWorkerMiddleName(): ?string
    {
        return $this->WorkerMiddleName;
    }

    public function setWorkerMiddleName(string $WorkerMiddleName): self
    {
        $this->WorkerMiddleName = $WorkerMiddleName;

        return $this;
    }

    public function getWorkerLastName(): ?string
    {
        return $this->WorkerLastName;
    }

    public function setWorkerLastName(string $WorkerLastName): self
    {
        $this->WorkerLastName = $WorkerLastName;

        return $this;
    }

    public function getWorkerPhone(): ?string
    {
        return $this->WorkerPhone;
    }

    public function setWorkerPhone(string $WorkerPhone): self
    {
        $this->WorkerPhone = $WorkerPhone;

        return $this;
    }

    public function getBay(): ?Bay
    {
        return $this->Bay;
    }

    public function setBay(?Bay $Bay): self
    {
        $this->Bay = $Bay;

        return $this;
    }

    public function getTypeOfWork(): ?TypeOfWork
    {
        return $this->TypeOfWork;
    }

    public function setTypeOfWork(?TypeOfWork $TypeOfWork): self
    {
        $this->TypeOfWork = $TypeOfWork;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setWorker($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getWorker() === $this) {
                $service->setWorker(null);
            }
        }

        return $this;
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn btn-outline-danger" style="margin-top: 1em;">Удалить</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-primary" style="margin-bottom: 1em;">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать услугу{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Редактор услуги</h1>

        {{ include('service/_form.html.twig', {'button_label': 'Обновить'}) }}

        <a href="{{ path('app_service_index') }}" class="btn btn-primary">Вернуться к услугам</a>

        {{ include('service/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Услуги{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Услуги</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Описание услуги</th>
                <th>Стоимость услуги</th>
                <th>Дата завершения</th>
            </tr>
            </thead>
            <tbody>
            {% for service in services %}
                <tr>
                    <td>
                        <a href="{{ path('app_service_show', {'id': service.id}) }}">{{ service.serviceDescription }}</a>
                    </td>
                    <td>{{ service.ServicePrice }}</td>
                    <td>{{ service.ServiceCompleteDate ? service.ServiceCompleteDate|date('Y-m-d') : '' }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_main_index') }}" class="btn btn-outline-success">На главную</a>
    </div>
{% endblock %}

templates/service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавить услугу{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Добавить услугу</h1>

        {{ include('service/_form.html.twig') }}

        <a href="{{ path('app_service_index') }}" class="btn btn-primary">Вернуться к услугам</a>
    </div>
{% endblock %}

templates/service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ service.serviceDescription }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>{{ service.serviceDescription }}</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Стоимость услуги</th>
                <td>{{ service.ServicePrice }}</td>
            </tr>
            <tr>
                <th>Дата завершения</th>
                <td>{{ service.ServiceCompleteDate ? service.ServiceCompleteDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>В каком боксе</th>
                <td>Бокс №{{ bay.id }} ({{ bay.bayType }})</td>
            </tr>
            <tr>
                <th>Кто занимается</th>
                <td><a href="{{ path('app_worker_show', {'id': worker.id}) }}" >{{ worker.workerMiddleName }} {{ worker.workerFirstName }} {{ worker.workerLastName }}</a></td>
            </tr>
            <tr>
                <th>К какому заказу относится</th>
                <td><a href="{{ path('app_custom_show', {'id': custom.id}) }}">{{ custom.carInformation }}</a></td>
            </tr>
            {% for material in materials %}
            <tr>
                <th><a href="{{ path('app_material_show', {'id': material.id}) }}">{{ material.materialName }}</a></th>
                <td>{{ material.materialAmount }} {{ material.materialMeasure }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_service_index') }}" class="btn btn-primary">Вернуться к услугам</a>

        <a href="{{ path('app_service_edit', {'id': service.id}) }}" class="btn btn-outline-secondary">Редактировать</a>

        <a href="{{ path('app_material_new', {'service_id': service.id}) }}"
           class="btn btn-outline-success" role="button">Добавить материал</a>

        {{ include('service/_delete_form.html.twig') }}
    </div>
{% endblock %}