src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $CustomerPhone;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $CustomerFirstName;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $CustomerMiddleName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $CustomerLastName;

    /**
     * @ORM\OneToMany(targetEntity=Custom::class, mappedBy="Client", orphanRemoval=true)
     */
    private $Custom;

    public function __construct()
    {
        $this->Custom = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomerPhone(): ?string
    {
        return $this->CustomerPhone;
    }

    public function setCustomerPhone(string $CustomerPhone): self
    {
        $this->CustomerPhone = $CustomerPhone;

        return $this;
    }

    public function getCustomerFirstName(): ?string
    {
        return $this->CustomerFirstName;
    }

    public function setCustomerFirstName(string $CustomerFirstName): self
    {
        $this->CustomerFirstName = $CustomerFirstName;

        return $this;
    }

    public function getCustomerMiddleName(): ?string
    {
        return $this->CustomerMiddleName;
    }

    public function setCustomerMiddleName(string $CustomerMiddleName): self
    {
        $this->CustomerMiddleName = $CustomerMiddleName;

        return $this;
    }

    public function getCustomerLastName(): ?string
    {
        return $this->CustomerLastName;
    }

    public function setCustomerLastName(?string $CustomerLastName): self
    {
        $this->CustomerLastName = $CustomerLastName;

        return $this;
    }

    /**
     * @return Collection<int, Custom>
     */
    public function getCustom(): Collection
    {
        return $this->Custom;
    }

    public function addCustom(Custom $custom): self
    {
        if (!$this->Custom->contains($custom)) {
            $this->Custom[] = $custom;
            $custom->setClient($this);
        }

        return $this;
    }

    public function removeCustom(Custom $custom): self
    {
        if ($this->Custom->removeElement($custom)) {
            // set the owning side to null (unless already changed)
            if ($custom->getClient() === $this) {
                $custom->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Custom.php
<?php

namespace App\Entity;

use App\Repository\CustomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomRepository::class)
 */
class Custom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $CarInformation;

    /**
     * @ORM\Column(type="date")
     */
    private $OrderDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderEndDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderPayDate;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="Custom")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Custom", orphanRemoval=true)
     */
    private $Service;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarInformation(): ?string
    {
        return $this->CarInformation;
    }

    public function setCarInformation(string $CarInformation): self
    {
        $this->CarInformation = $CarInformation;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->OrderDate;
    }

    public function setOrderDate(\DateTimeInterface $OrderDate): self
    {
        $this->OrderDate = $OrderDate;

        return $this;
    }

    public function getOrderEndDate(): ?\DateTimeInterface
    {
        return $this->OrderEndDate;
    }

    public function setOrderEndDate(?\DateTimeInterface $OrderEndDate): self
    {
        $this->OrderEndDate = $OrderEndDate;

        return $this;
    }

    public function getOrderPayDate(): ?\DateTimeInterface
    {
        return $this->OrderPayDate;
    }

    public function setOrderPayDate(?\DateTimeInterface $OrderPayDate): self
    {
        $this->OrderPayDate = $OrderPayDate;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setCustom($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getCustom() === $this) {
                $service->setCustom(null);
            }
        }

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ServiceDescription;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\GreaterThan(0)
     */
    private $ServicePrice;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ServiceCompleteDate;

    /**
     * @ORM\ManyToOne(targetEntity=Custom::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Custom;

    /**
     * @ORM\ManyToOne(targetEntity=Bay::class, inversedBy="Service")
     */
    private $Bay;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfWork::class, inversedBy="Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TypeOfWork;

    /**
     * @ORM\ManyToOne(targetEntity=Worker::class, inversedBy="Service")
     */
    private $Worker;

    /**
     * @ORM\OneToMany(targetEntity=Material::class, mappedBy="Service")
     */
    private $Material;

    public function __construct()
    {
        $this->Material = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getServiceDescription(): ?string
    {
        return $this->ServiceDescription;
    }

    public function setServiceDescription(?string $ServiceDescription): self
    {
        $this->ServiceDescription = $ServiceDescription;

        return $this;
    }

    public function getServicePrice(): ?string
    {
        return $this->ServicePrice;
    }

    public function setServicePrice(string $ServicePrice): self
    {
        $this->ServicePrice = $ServicePrice;

        return $this;
    }

    public function getServiceCompleteDate(): ?\DateTimeInterface
    {
        return $this->ServiceCompleteDate;
    }

    public function setServiceCompleteDate(?\DateTimeInterface $ServiceCompleteDate): self
    {
        $this->ServiceCompleteDate = $ServiceCompleteDate;

        return $this;
    }

    public function getCustom(): ?Custom
    {
        return $this->Custom;
    }

    public function setCustom(?Custom $Custom): self
    {
        $this->Custom = $Custom;

        return $this;
    }

    public function getBay(): ?Bay
    {
        return $this->Bay;
    }

    public function setBay(?Bay $Bay): self
    {
        $this->Bay = $Bay;

        return $this;
    }

    public function getTypeOfWork(): ?TypeOfWork
    {
        return $this->TypeOfWork;
    }

    public function setTypeOfWork(?TypeOfWork $TypeOfWork): self
    {
        $this->TypeOfWork = $TypeOfWork;

        return $this;
    }

    public function getWorker(): ?Worker
    {
        return $this->Worker;
    }

    public function setWorker(?Worker $Worker): self
    {
        $this->Worker = $Worker;

        return $this;
    }

    /**
     * @return Collection<int, Material>
     */
    public function getMaterial(): Collection
    {
        return $this->Material;
    }

    public function addMaterial(Material $material): self
    {
        if (!$this->Material->contains($material)) {
            $this->Material[] = $material;
            $material->setService($this);
        }

        return $this;
    }

    public function removeMaterial(Material $material): self
    {
        if ($this->Material->removeElement($material)) {
            // set the owning side to null (unless already changed)
            if ($material->getService() === $this) {
                $material->setService(null);
            }
        }

        return $this;
    }
}

src/Form/CustomType.php
<?php

namespace App\Form;

use App\Entity\Custom;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\DataTransformer\ClientToStringTransformer;

class CustomType extends AbstractType
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('CarInformation')
            ->add('OrderDate')
            ->add('OrderEndDate')
            ->add('OrderPayDate')
            ->add('Client', TextType::class, array(
                // сообщение валидации при ошибке преобразователя данных
                'invalid_message' => 'That is not a valid issue number',
            ));

        $builder->get('Client')->addModelTransformer(new ClientToStringTransformer($this->em));

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Custom::class,
            'client_id' => 0,
        ]);
    }
}

src/Controller/CustomController.php
<?php

namespace App\Controller;

use App\Entity\Custom;
use App\Form\CustomType;
use App\Repository\ClientRepository;
use App\Repository\CustomRepository;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/custom")
 */
class CustomController extends AbstractController
{
    /**
     * @Route("/", name="app_custom_index", methods={"GET"})
     */
    public function index(CustomRepository $customRepository): Response
    {
        return $this->render('custom/index.html.twig', [
            'customs' => $customRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_custom_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CustomRepository $customRepository, ClientRepository $clientRepository): Response
    {
        $custom = new Custom();
        $client_id=$request->query->get('client_id');
        $client = $clientRepository->findBy(['id' => $client_id]);
        $client=$client[0];
        $custom->setClient($client);
        $form = $this->createForm(CustomType::class, $custom, ['client_id' => $client_id]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customRepository->add($custom, true);
            return $this->redirectToRoute('app_custom_show', ['id' => $custom->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('custom/new.html.twig', [
            'custom' => $custom,
            'form' => $form,
            'client' =>$client,
        ]);
    }

    /**
     * @Route("/{id}", name="app_custom_show", methods={"GET"})
     */
    public function show(Custom $custom): Response
    {
        $client=$custom->getClient();
        $services= $custom->getService()->getValues();
        return $this->render('custom/show.html.twig', [
            'custom' => $custom,
            'client' => $client,
            'services' => $services,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_custom_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Custom $custom, CustomRepository $customRepository): Response
    {
        $form = $this->createForm(CustomType::class, $custom);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customRepository->add($custom, true);

            return $this->redirectToRoute('app_custom_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('custom/edit.html.twig', [
            'custom' => $custom,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_custom_delete", methods={"POST"})
     */
    public function delete(Request $request, Custom $custom, CustomRepository $customRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$custom->getId(), $request->request->get('_token'))) {
            $customRepository->remove($custom, true);
        }

        return $this->redirectToRoute('app_custom_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/custom/_delete_form.html.twig
<form method="post" action="{{ path('app_custom_delete', {'id': custom.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ custom.id) }}">
    <button class="btn btn-outline-danger" style="margin-top: 1em;">Удалить</button>
</form>

templates/custom/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/custom/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование заказа{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Редактор заказа</h1>

        {{ include('custom/_form.html.twig', {'button_label': 'Обновить'}) }}

        <a href="{{ path('app_custom_index') }}">Вернуться к заказам</a>

        {{ include('custom/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/custom/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Наши заказы{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Наши заказы</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Информация о машинах</th>
                <th>Дата начала</th>
                <th>Дата окончания</th>
                <th>Дата оплаты</th>
            </tr>
            </thead>
            <tbody>
            {% for custom in customs %}
                <tr>
                    <td>
                        <a href="{{ path('app_custom_show', {'id': custom.id}) }}">{{ custom.CarInformation }}</a>
                    </td>
                    <td>{{ custom.OrderDate ? custom.OrderDate|date('Y-m-d') : '' }}</td>
                    <td>{{ custom.OrderEndDate ? custom.OrderEndDate|date('Y-m-d') : '' }}</td>
                    <td>{{ custom.OrderPayDate ? custom.OrderPayDate|date('Y-m-d') : '' }}</td>

                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_main_index') }}" class="btn btn-outline-success">На главную</a>
    </div>
{% endblock %}

templates/custom/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление заказа{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Добавление заказа</h1>

        {{ include('custom/_form.html.twig') }}

        <a href="{{ path('app_custom_index') }}" class="btn btn-outline-primary" style="margin-top: 1em;">Вернуться к заказам</a>
    </div>
{% endblock %}

templates/custom/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ custom.carInformation }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>{{ custom.carInformation }}</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Дата начала</th>
                <td>{{ custom.OrderDate ? custom.OrderDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Дата окончания</th>
                <td>{{ custom.OrderEndDate ? custom.OrderEndDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Дата оплаты</th>
                <td>{{ custom.OrderPayDate ? custom.OrderPayDate|date('Y-m-d') : '' }}</td>
            </tr>
            {% for service in services %}
            <tr>
                <th>{{ service.serviceDescription }}</th>
                <td><a href="{{ path('app_service_show', {'id': service.id}) }}" class="btn btn-outline-primary">К услуге</a></td>
            </tr>
            {% endfor %}
            <tr>
                <th>{{ client.customerMiddleName }} {{ client.customerFirstName }} {{ client.customerLastName }}</th>
                <td><a href="{{ path('app_client_show', {'id': client.id}) }}" class="btn btn-outline-primary">К заказчику</a></td>
            </tr>
            </tbody>
        </table>

        <a href="{{ path('app_custom_index') }}" class="btn btn-primary">Вернуться к заказам</a>

        <a href="{{ path('app_custom_edit', {'id': custom.id}) }}" class="btn btn-outline-secondary">Редактировать</a>

        <a href="{{ path('app_service_new', {'custom_id': custom.id}) }}"
           class="btn btn-outline-success" role="button">Добавить услугу</a>

        {{ include('custom/_delete_form.html.twig') }}
    </div>
{% endblock %}