src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $CustomerPhone;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $CustomerFirstName;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $CustomerMiddleName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $CustomerLastName;

    /**
     * @ORM\OneToMany(targetEntity=Custom::class, mappedBy="Client", orphanRemoval=true)
     */
    private $Custom;

    public function __construct()
    {
        $this->Custom = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomerPhone(): ?string
    {
        return $this->CustomerPhone;
    }

    public function setCustomerPhone(string $CustomerPhone): self
    {
        $this->CustomerPhone = $CustomerPhone;

        return $this;
    }

    public function getCustomerFirstName(): ?string
    {
        return $this->CustomerFirstName;
    }

    public function setCustomerFirstName(string $CustomerFirstName): self
    {
        $this->CustomerFirstName = $CustomerFirstName;

        return $this;
    }

    public function getCustomerMiddleName(): ?string
    {
        return $this->CustomerMiddleName;
    }

    public function setCustomerMiddleName(string $CustomerMiddleName): self
    {
        $this->CustomerMiddleName = $CustomerMiddleName;

        return $this;
    }

    public function getCustomerLastName(): ?string
    {
        return $this->CustomerLastName;
    }

    public function setCustomerLastName(?string $CustomerLastName): self
    {
        $this->CustomerLastName = $CustomerLastName;

        return $this;
    }

    /**
     * @return Collection<int, Custom>
     */
    public function getCustom(): Collection
    {
        return $this->Custom;
    }

    public function addCustom(Custom $custom): self
    {
        if (!$this->Custom->contains($custom)) {
            $this->Custom[] = $custom;
            $custom->setClient($this);
        }

        return $this;
    }

    public function removeCustom(Custom $custom): self
    {
        if ($this->Custom->removeElement($custom)) {
            // set the owning side to null (unless already changed)
            if ($custom->getClient() === $this) {
                $custom->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Custom.php
<?php

namespace App\Entity;

use App\Repository\CustomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomRepository::class)
 */
class Custom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $CarInformation;

    /**
     * @ORM\Column(type="date")
     */
    private $OrderDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderEndDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $OrderPayDate;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="Custom")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Custom", orphanRemoval=true)
     */
    private $Service;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarInformation(): ?string
    {
        return $this->CarInformation;
    }

    public function setCarInformation(string $CarInformation): self
    {
        $this->CarInformation = $CarInformation;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->OrderDate;
    }

    public function setOrderDate(\DateTimeInterface $OrderDate): self
    {
        $this->OrderDate = $OrderDate;

        return $this;
    }

    public function getOrderEndDate(): ?\DateTimeInterface
    {
        return $this->OrderEndDate;
    }

    public function setOrderEndDate(?\DateTimeInterface $OrderEndDate): self
    {
        $this->OrderEndDate = $OrderEndDate;

        return $this;
    }

    public function getOrderPayDate(): ?\DateTimeInterface
    {
        return $this->OrderPayDate;
    }

    public function setOrderPayDate(?\DateTimeInterface $OrderPayDate): self
    {
        $this->OrderPayDate = $OrderPayDate;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Service $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
            $service->setCustom($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->Service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getCustom() === $this) {
                $service->setCustom(null);
            }
        }

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('CustomerPhone')
            ->add('CustomerFirstName')
            ->add('CustomerMiddleName')
            ->add('CustomerLastName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use App\Repository\CustomRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="app_client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_client_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ClientRepository $clientRepository): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_client_show", methods={"GET"})
     */
    public function show(Client $client, CustomRepository $customRepository): Response
    {
        $customs=$customRepository->findBy(['Client' => $client->getId()]);
        return $this->render('client/show.html.twig', [
            'client' => $client,
            'customs' => $customs,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_client_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $clientRepository->remove($client, true);
        }

        return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('app_client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-outline-danger">Удалить</button>
</form>

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование клиента{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Редактор клиента</h1>

        {{ include('client/_form.html.twig', {'button_label': 'Обновить'}) }}

        <div class="d-grid gap-2 d-md-block">
            <a href="{{ path('app_client_index') }}" class="btn btn-outline-primary "
               style="margin-top: 1em; margin-bottom: 1em">К сипску клиентов</a>

            {{ include('client/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Наши клиенты{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Наши клиенты</h1>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for client in clients %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ client.customerPhone }}</h5>
                            <p class="card-text">{{ client.customerMiddleName }} {{ client.customerFirstName }} {{ client.customerLastName }}</p>
                            <p>
                                <a href="{{ path('app_client_show', {'id': client.id}) }}" class="btn btn-outline-primary">Подробнее</a>
                                <a href="{{ path('app_client_edit', {'id': client.id}) }}" class="btn btn-outline-secondary">Редактировать</a>
                            </p>
                        </div>
                    </div>
                </div>

            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
        </div>
        <p style="margin-top: 1em">
            <a href="{{ path('app_client_new') }}" class="btn btn-primary">Добавить клиента</a>
            <a href="{{ path('app_main_index') }}" class="btn btn-outline-success">На главную</a>
        </p>
    </div>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление нового клиента{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Добавить нового клиента</h1>

        {{ include('client/_form.html.twig') }}

        <a href="{{ path('app_client_index') }}" class="btn btn-outline-primary" style="margin-top: 1em;">К списку
            клиентов</a>
    </div>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ client.customerMiddleName }} {{ client.customerFirstName }} {{ client.customerLastName }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>{{ client.customerMiddleName }} {{ client.customerFirstName }} {{ client.customerLastName }}</h1>

        <p>Телефон: {{ client.customerPhone }}</p>
        <h3>Заказы:</h3>
        {% for custom in customs %}
            <p>
                <a href="{{ path('app_custom_show', {'id': custom.id}) }}">{{ custom.carInformation }}</a>
            </p>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}

        <p style="margin-bottom: 1em; margin-top: 1em;">
            <a href="{{ path('app_client_index') }}" class="btn btn-outline-primary">К списку клиентов</a>

            <a href="{{ path('app_client_edit', {'id': client.id}) }}"
               class="btn btn-outline-secondary">Редактировать</a>

            <a href="{{ path('app_custom_new', {'client_id': client.id}) }}"
               class="btn btn-outline-success" role="button">Добавить заказ</a>
        </p>
        {{ include('client/_delete_form.html.twig') }}
    </div>
{% endblock %}